# Generated by Django 5.2.6 on 2025-09-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='莨夂､ｾ蜷・')),
                ('address', models.TextField(verbose_name='菴乗園')),
                ('phone', models.CharField(max_length=20, verbose_name='髮ｻ隧ｱ逡ｪ蜿ｷ')),
                ('email', models.EmailField(max_length=254, verbose_name='繝｡繝ｼ繝ｫ繧｢繝峨Ξ繧ｹ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '莨夂､ｾ諠・\uf8f0ｱ',
                'verbose_name_plural': '莨夂､ｾ諠・\uf8f0ｱ',
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='蜍滄寔繧ｿ繧､繝医Ν')),
                ('description', models.TextField(verbose_name='蜍滄寔蜀・ｮｹ')),
                ('requirements', models.TextField(verbose_name='蠢懷供雉・\uf8f0ｼ')),
                ('is_active', models.BooleanField(default=True, verbose_name='蜈ｬ髢狗憾諷・')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '謗｡逕ｨ諠・\uf8f0ｱ',
                'verbose_name_plural': '謗｡逕ｨ諠・\uf8f0ｱ',
                'ordering': ['-created_at'],
            },
        ),
    ]
